### ISSUE TITLE
Plugin cannot connect to MT service

### ISSUE THREAD

**Issue by paulmandal** [paulmandal/atak-forwarder#173]
Opening this issue for tracking purposes, in 2.0.6 and later versions of the plugin the plugin icon will turn to "SVC" in red letters when in this state.

If you are having this issue please post your Android version, plugin version, and ATAK version to this issue.

**Comment by cpt518** [comment]
Good news, I see the svc icon marked read now but it is now telling me it won’t connect to meshtastic. Meshtastic has been reinstalled, as has ATAK/plugin.

Atak4.8.1.17
Meshtastic 2.1.4
Android 13
ATAK forwarder 2.0.6 (most current)

**Comment by paulmandal** [comment]
@cpt518 try with Meshtastic 2.1.8 (app and firmware)
You may also get the message `Unable to start service Intent { cmp=com.geeksville.mesh/.service.MeshService } U=0: not found` in your `logcat` output from your device, that is what I'm seeing on the device I can replicate the issue on at least.

**Comment by Josh-SMU** [comment]
Everything works for me but I also get the toast notification saying it cant connect to the Meshtastic service. Seems like a false positive as everything is working otherwise.

**Comment by paulmandal** [comment]
Thanks for the post @Josh-SMU
That Toast most likely fires as the plugin is starting up before it's connected to the service, if you get the SVC icon in red the issue is persisting.

**Comment by binarylandscapes** [comment]
I have this issue after updating everything after a long period.
MT 2.1.4
FW 2.1.5
ATAK 4.8.1.19
Plugin 2.0.6-1-4.8.1
Android 13

**Comment by fastbuckink** [comment]
new to this, so i might be doing something totally wrong.
i have meshtastic working and communicating between devices. with atak i get the red svc
android 13
meshtastic 2.1.10
atak 4.8.1.19
tbeam 2.1.8
forwarder 2.0.6 4.8.1

sam isue with tablet runnung android 13 as well

**Comment by binarylandscapes** [comment]
> 

Same with MT 2.1.11

**Comment by Jkjvinn** [comment]
Seems everyone that have this problem is running android 13
Android 13
MT 2.1.10
ATAK 4.8.1.19
FW 2.0.6 4.8.1

**Comment by SCWhite** [comment]
I think this issue is on ATAK 4.8.1

(when disabling "Plugin Manages Device")
I can connect and let those node see/communicate each other on:
Android 12/13
Meshtastic app: fdroidRelease-2.1.0
Meshtastic FW: 2.1.11
ATAK.Forwarder: 2.0.6-1-4.7.0
ATAK 4.7.0

but when I change to  ATAK 4.8.1 with Forwarder 2.0.6-1-4.8.1
I always got SVC error

**Comment by Jkjvinn** [comment]
I got the apk from pureapk because I did not want to open an account on a goverment website, I'll ask my friend to use his account to download a new file.

**Comment by Jkjvinn** [comment]
Well 1 out of 4 of my devices , the one is running android 9 is working, the one running 12 and the two running 13 does not work.

**Comment by Jkjvinn** [comment]
@paulmandal is it possible for you to check if its the newer android 12 and 13 permission system messing with the plugin?

**Comment by Jkjvinn** [comment]
Good news, got it to work, I had to use this set up 
ATAK 4.7.0.4 from tak.gov 
Radio firmware 2.1.10
Meshtastic App 2.0.21
Forwarder plugin 2.0.5
on Android 13 on Google pixel 7 pro and Google pixel 4 XL

**Comment by Tyler-2** [comment]
Doesn't work:

Android 13
ATAK Forwarder: 2.0.6
ATAK version: 4.8.1.19 (playstore)
Meshtastic app: 2.1.9
Meshtastic firmware: 2.1.5 and 2.1.11

**Comment by Jkjvinn** [comment]
> 

Do not use playstore version, the tak.gov version is more than 250mb and the play store version is less than 100mb, they cut stuff out.

**Comment by cpt518** [comment]
Still struggling with the various settings but continue to get hung up on the “service disconnected” while working thru all the various combos.

cant update the firmware for my tbeam due to errors with the web flasher so I’m stuck with the 2.0.6 FW the device came with. Any recs in which version of the forwarder/app would work best on that firmware? I was thinking the 2.0 release

**Comment by paulmandal** [comment]
It looks like this issue is confined to ATAK 4.8.x+, using 4.7.0.4 should work for now.

**Comment by Tahkis** [comment]
Did some extensive testing today. Not exactly sure where the problem is but was able to set things up and working and most importantly replicate the process.

My setup (x2)
Galaxy XCover 4s running Android 11 w OneUI 3.1
ATAK v4.8.1.27 playstore
ATAK Forwarder 2.0.6-4.8.1
Meshtastic 2.1.15
LilyGo t-echo v2.1.14.99a31c1

Did the BT pairing first w Android BT tool.
Then set up the T-ECHOs to Meshtastic.
Confirmed w Meshtastic sending messages.
Then loaded the  ATAK Forwarder plugin in ATAK.
In Forwarder pref refreshed devices and selected paired t-echo and region.
Ensured the Plugin Manages Devices is on.
Backed out of setting onto map.

After this I could see blue led blinking on both T-Echos. Apparently something was configured down and had to give a reboot for both (2x boot button taps on echos).

After reboot quit and relaunch ATAK > done and both get configured for use.

HOWEVER, since my XCover 4s devices do not support QR reading, I can not set up a common channel with Forwarder.IS THERE  any other way to export and import the a Forwarder created Meshtastic channel data from device to device but only the QR scan?

**Comment by Nordic2199** [comment]
Can anybody give me an explanation where you flash your devices with these old versions?
My biggest problem is that the web flasher only allows to flash newer firmwares...
The oldest one is 2.1.18

**Comment by TermnlSgt** [comment]
@Nordic2199 https://web.esphome.io/

**Comment by TermnlSgt** [comment]
> Can anybody give me an explanation where you flash your devices with these old versions?
> My biggest problem is that the web flasher only allows to flash newer firmwares...
> The oldest one is 2.1.18

@Nordic2199 https://web.esphome.io/

**Comment by Nordic2199** [comment]
> Good news, got it to work, I had to use this set up ATAK 4.7.0.4 from tak.gov Radio firmware 2.1.10 Meshtastic App 2.0.21 Forwarder plugin 2.0.5 on Android 13 on Google pixel 7 pro and Google pixel 4 XL

Had the same settings except of the ATAK version - got the ATAK 4.7.0.4 from playstore and it doesn`t worked :(

**Comment by SCWhite** [comment]
@Nordic2199 
you need ATAK 4.7.0 from [www.tak.gov](https://tak.gov/)
Playstore version doesn't work

**Comment by Nordic2199** [comment]
> @Nordic2199 you need ATAK 4.7.0 from [https://tak.gov](https://tak.gov/) Playstore version doesn't work

But the oldest version that is possible to download is 4.8.1

**Comment by SCWhite** [comment]
@Nordic2199  Ah, I see.
They seems to took down the older version.
Then there is nothing we can do right now, maybe we can send @paulmandal some coffee and hope for the best?

**Comment by Jkjvinn** [comment]
> > Good news, got it to work, I had to use this set up ATAK 4.7.0.4 from tak.gov Radio firmware 2.1.10 Meshtastic App 2.0.21 Forwarder plugin 2.0.5 on Android 13 on Google pixel 7 pro and Google pixel 4 XL
> 
> Are you able to provide the ATAK version? ;)

Yes but use it at your own risk, scan it before use.
https://drive.google.com/drive/folders/13rqNxuNbXmhe1qjagzwKDS76Mpa37oB0

**Comment by Nordic2199** [comment]
> > > Good news, got it to work, I had to use this set up ATAK 4.7.0.4 from tak.gov Radio firmware 2.1.10 Meshtastic App 2.0.21 Forwarder plugin 2.0.5 on Android 13 on Google pixel 7 pro and Google pixel 4 XL
> > 
> > 
> > Are you able to provide the ATAK version? ;)
> 
> Yes but use it at your own risk, scan it before use. https://drive.google.com/drive/folders/13rqNxuNbXmhe1qjagzwKDS76Mpa37oB0

Thank you a lot 
Works perfectly on Samsung S20 and S22
