### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by kb1isz** [paulmandal/atak-forwarder#30]
From the Readme:
Automatically adjust link speed / range based on # of lost messages
Use T-Beam as a GPS source (if it proves to be more accurate than the phone's)
Message IDs and receipt confirmation
Improve chat message shrinking further
Smarter sending -- Map Markers get higher priority unless PLI has not gotten sent in ~5 minutes
Smarter sending -- Send a list of map markers to group, other clients can reply with which marker they are missing, build up a list of missing markers if more than 1 person is missing send to group, otherwise send to individuals
Needs more real-world stability testing
Re-add GoTenna support with a proper abstraction for communication layer

Some additional from me.
Find my T-Beam: Have keep-alive sent to local T-beam. If keep-alive is lost, T-Beam will broadcast it's location at a preset interval and set a marker where it was when it was lost and where it last successfully got a keep-alive.

Message queuing and prioritization: Might just be what you have above, include things like rate limits etc.

PLI rounding: If last PLI was within a certain distance discard it unless it's been a preset time.

**Comment by paulmandal** [comment]
hey re-reading this feature request, this would require changes to the `Meshtastic-device` source since the T-Beam would be broadcasting its location. It would also require a Meshtastic device to receive the lost T-Beams location.

I have implemented a feature where any Meshtastic device your channel that does not have an associated ATAK UID will be displayed on the map using the location it broadcasts, this might meet your needs. Let me know what you think!

**Comment by kb1isz** [comment]
Sorry if it wasn't clear, the use case was exactly as you described. Let's say I have the tbeam clipped onto a backpack and it falls off without me noticing right away. I do see your point though it sounds like it would require the meshtastic firmware to be changed.

**Comment by paulmandal** [comment]
Closing this out since it will require Meshtastic-device mods which is outside the scope of this project and to keep the issues log clean
