### ISSUE TITLE
Proposed simplification of CoT event dispatching

### ISSUE THREAD

**Issue by a-f-G-U-C** [paulmandal/atak-forwarder#41]
The change from PR #39 works as intended and fixes issue #35 (but not #34 since it only dispatches **internally**). However, since API methods are now used that provide appropriate abstraction, the additional layer of abstraction via `mCotDispatcher` seems to me somewhat redundant. 

I suggest that rewriting the function `retransmitCotToLocalhost()` to invoke the dispatcher methods directly could reduce some of the complexity without impacting the code structure - and fix issue #34 in one fell swoop.

Here's what worked well for me (in [InboundMessageHandler.java](https://github.com/paulmandal/atak-forwarder/blob/develop/app/src/main/java/com/paulmandal/atak/forwarder/handlers/InboundMessageHandler.java) ):
```
import com.atakmap.android.cot.CotMapComponent;
[...]

    public void retransmitCotToLocalhost(CotEvent cotEvent) {
        CotMapComponent.getInternalDispatcher().dispatch(cotEvent);
        CotMapComponent.getExternalDispatcher().dispatch(cotEvent);
    }
```
(the second line dispatches the CoT event **externally**, fixing issue #34)

I'm reluctant to submit a PR around this change since it should also include a cleanup of the `InboundMessageHandler` class - a task requiring a level of familiarity with your code that I don't have yet. :) But I hope it helps nonetheless.

**Comment by paulmandal** [comment]
Thanks for letting me know that this solution wasn't complete!

https://github.com/paulmandal/atak-forwarder/pull/43 fixes this by using both the internal and external `CotDispatcher`s in `InboundMessageHandler.retransmitCotToLocalhost(CotEvent)`

I left the `mInternalCotDispatcher` and `mExternalCotDispatcher` abstraction in `InboundMessageHandler` because it allows for the injection of mocks through the constructor for those dependencies if I ever get around to writing testing code for this codebase.

**Comment by a-f-G-U-C** [comment]
I had a feeling that I was missing something important! :)
Tested and works as intended, so I'll close this issue now.
