### ISSUE TITLE
Is the patched Meshtastic app still required?

### ISSUE THREAD

**Issue by a-f-G-U-C** [paulmandal/atak-forwarder#47]
I noticed I've been accidentally running the plugin with the mainline Meshtastic-Android app with no apparent issues. 

Is the requirement from the README (under **"Build + Install Meshtastic"**) still relevant, or have the changes been merged into the mainline code in the meanwhile?

**Comment by paulmandal** [comment]
My PR: https://github.com/meshtastic/Meshtastic-Android/pull/172 was merged about 2 weeks ago but I don't think they have done a release since then. Are you seeing an error in logcat about a `Handler` not being able to be created on a thread that has not called `Looper.prepare()`? Did you set the device up previously in the Meshtastic app?

**Comment by a-f-G-U-C** [comment]
I was running a self-compiled APK, post Looper fix. This explains why it "just worked" :)

I suggest updating the README instructions to point to the meshtastic repo, which now includes your fix, along with a few other useful fixes and features not included in your fork.

**Comment by paulmandal** [comment]
Good call, updated the README here: https://github.com/paulmandal/atak-forwarder/pull/55
