### ISSUE TITLE
Suggestion: do not name the radio with the owner's callsign

### ISSUE THREAD

**Issue by a-f-G-U-C** [paulmandal/atak-forwarder#53]
Currently, the plugin sets (and stubbornly re-sets) the radio name to the ATAK callsign. I think the code responsible for this is around here:

https://github.com/paulmandal/atak-forwarder/blob/f443f6c96cefb9726a914871439fa46467b198b2/app/src/main/java/com/paulmandal/atak/forwarder/channel/UserInfo.java#L15-L16

This is not the best approach, for two reasons:
1) when the radio is peered to the EUD, its name is irrelevant from an ATAK perspective - the callsign of the unit is set in the CoT packets
2) however, when the radio and the ATAK EUD become **separated** and the radio starts beaconing stand-alone, the EUD and the radio will plot on the map as two separate units with the **same callsign**, which is not ideal

I suggest, instead of setting the radio name to the unit callsign, to set it to a **variation** of the callsign, indicating that it is a related, but distinct unit. 

For example, if the ATAK callsign is `ALICE` and the radio's 16-bit node ID is `0xc4f3`, set the radio name to **`ALICE-MX-c4f3`**. 

This will ensure that the radio's ownership information is retained (to aid in a recovery operation), while preventing the radio from accidentally *impersonating its owner* in the process. The numeric suffix enables even multiple lost units to be individually identified.

**Comment by paulmandal** [comment]
Thanks for the suggestion. I will get this implemented in the next few days -- I'm trying to take a small break after the ATAK conference.

For #2 I'm not sure how a Meshtastic device that was being used as a main comm. device will behave when separated. When we set up the main comm. device it's configured to only send a location update once per hour: https://github.com/paulmandal/atak-forwarder/blob/main/app/src/main/java/com/paulmandal/atak/forwarder/comm/commhardware/MeshtasticCommHardware.java#L384 since ATAK will be sending location updates.

It might make sense to have the Meshtastic-device code have two reporting intervals, one for when it's connected to a phone/tablet and another for when it's solo.

I'll make the naming changes soon and think about the best way to solve this, the people running the Meshtastic project have been really responsive so if it requires changes there that shouldn't be a barrier.

**Comment by paulmandal** [comment]
Implemented here: https://github.com/paulmandal/atak-forwarder/pull/57

**Comment by a-f-G-U-C** [comment]
Tested and working as intended. Thank you!
